#ifndef ASHURTUNNELVICO100_GLOBAL_H
#define ASHURTUNNELVICO100_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ASHURTUNNELVICO100_LIBRARY)
#  define ASHURTUNNELVICO100_EXPORT Q_DECL_EXPORT
#else
#  define ASHURTUNNELVICO100_EXPORT Q_DECL_IMPORT
#endif

#endif // ASHURTUNNELVICO100_GLOBAL_H
